version: '2'
services:
  openapi.yangarch.net:
    container_name: openapi.yangarch.net
    volumes:
      - ./app:/app
    ports:
      - "19080:80"
    build: .
    environment:
      CREDENTIAL_PATH: /credentials
